Week 4
rehmanali17/google-form-clone pull request #2
Opened 2022-02-20 18:25 UTC by rehmanali17

2022-02-22 06:41 UTC, rizwan-liaqat requested changes

2022-02-22 06:41 UTC, rizwan-liaqat commented on client/src/app/components/create-form/create-form-questions/actions-container/actions-container.component.html
> +        <span [ngClass]="{ 'dark-text-color': true }">Required</span>
use darkModeEnabled instead of hardcoded true

2022-02-22 06:41 UTC, rizwan-liaqat commented on client/src/app/components/create-form/create-form.component.ts
> +            if (mode === true) {
we can remove if else using the following line of code:
this.darkModeEnabled = mode;

and if you want to check either mode is undefined or not then you can do this:
this.darkModeEnabled = mode ? true : false;

2022-02-22 06:41 UTC, rizwan-liaqat commented on client/src/app/components/create-form/create-form.component.ts
>              if (dialogBoxState.formDialogBox.status === true) {
what is the reason behind checking "dialogBoxState.formDialogBox.status === true" instead of only "if (dialogBoxState.formDialogBox.status)"?

2022-02-22 06:41 UTC, rizwan-liaqat commented on client/src/app/components/create-form/saved-form-dialog/saved-form-dialog.component.ts
> +        if (this.darkModeEnabled === true) {
same here, can't you use only this: if (this.darkModeEnabled)

2022-02-22 06:41 UTC, rizwan-liaqat commented on client/src/app/components/dashboard/dashboard.component.scss
> +// .spinner-container ::ng-deep .mat-progress-spinner circle,
remove commented code

2022-02-22 06:41 UTC, rizwan-liaqat commented on client/src/app/components/dashboard/dashboard.component.ts
> +        if (this.cookieService.get('payload')) {
can we have a constant for this string 'payload'?

2022-02-22 06:41 UTC, rizwan-liaqat commented on client/src/app/components/dashboard/dashboard.component.ts
>                      width: '375px',
do you think that this width will work on different screen size/resolution?

2022-02-22 06:41 UTC, rizwan-liaqat commented on client/src/app/components/dashboard/forms-list/form-header/form-header.component.html
> +                Title &nbsp;&nbsp;&nbsp;
can we use some margin or padding instead of &nbsp;

2022-02-22 06:41 UTC, rizwan-liaqat commented on client/src/app/components/dashboard/forms-list/form-header/form-header.component.html
> +            <!-- <button mat-menu-item (click)="handleSortForms('createdAt')">
please remove commented code

2022-02-22 06:41 UTC, rizwan-liaqat commented on client/src/app/components/dashboard/forms-list/forms-grid-item/forms-grid-item.component.ts
> +        const link = environment.baseURL + '/fill-form/' + id;
please create a constant for fill-form string

2022-02-22 06:41 UTC, rizwan-liaqat commented on client/src/app/components/dashboard/forms-list/forms-grid-item/forms-grid-item.component.ts
> +        if (element.tagName === 'BUTTON' || element.tagName === 'MAT-ICON') {
please use constants

2022-02-22 06:41 UTC, rizwan-liaqat commented on client/src/app/components/dashboard/forms-list/forms-list.component.ts
> +                this.loadImages = formState.forms[0].imageString === '' ? true : false;
please read about truthy and falsy statements

2022-02-22 06:41 UTC, rizwan-liaqat commented on client/src/app/constants.ts
> +    CREATE_FORM: '/user/create-form',
please change this route with /user/form and then for create use POST and for edit use PUT etc and don't use hyphens

2022-02-24 16:43 UTC, rehmanali17 commented on client/src/app/constants.ts
> +    CREATE_FORM: '/user/create-form',
AOA sir, I didn't understand what you want to say here. How can I use POST and PUT? Are you asking me something like this?
/user/form.         -> POST
/user/form          -> PUT
how can we do something like this. Can you please just write an example

2022-02-24 20:44 UTC, rizwan-liaqat commented on client/src/app/constants.ts
> +    CREATE_FORM: '/user/create-form',
yes you are right we can have the following routs:
POST -> /user/form (with post it shows that this is an endpoint which will create form)
PUT -> /user/form (with put it shows that this is an endpoint which will update form)

2023-11-18 07:02 UTC, merged